### ISSUE TITLE
sa-gen without gsuite?

### ISSUE THREAD

**Issue by gimpyestrada** [88lex/sa-gen#3]
I'd like to know if I can use this script when I don't have a gsuite account.  I get to the point where I need to add a GROUP_NAME and I'm stuck because I can't create groups as described.

**Comment by gimpyestrada** [comment]
I figured it out, the answer is yes you can use without a gsuite, but you have to create a google group.

**Comment by ayykamp** [comment]
Hey, Im kind of stuck on the same issue. How did you end up adding the service accounts to a group?
